-- Fix for profiles table
DROP TABLE IF EXISTS public.profiles CASCADE;

CREATE TABLE public.profiles (
  id uuid REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  username text,
  email text,
  phone text,
  avatar_url text,
  about text,
  is_online bool DEFAULT false,
  last_seen timestamptz,
  push_token text,
  public_key text,
  show_email bool DEFAULT false,
  show_phone bool DEFAULT false,
  current_session_id text,
  created_at timestamptz DEFAULT now(),
  bio text,
  gender text,
  show_bio bool DEFAULT true,
  allow_status_download bool DEFAULT false,
  last_lat numeric,
  last_long numeric,
  allow_screenshot bool DEFAULT true,
  dp_privacy text DEFAULT 'everyone',
  dp_selected_friends uuid[] DEFAULT '{}',
  hide_dp_in_search bool DEFAULT false,
  about_privacy text DEFAULT 'everyone'
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON profiles;
CREATE POLICY "Public profiles are viewable by everyone." ON profiles FOR SELECT USING (true);
DROP POLICY IF EXISTS "Users can update own profile." ON profiles;
CREATE POLICY "Users can update own profile." ON profiles FOR UPDATE USING (auth.uid() = id);


-- Fix for friendships table
DROP TABLE IF EXISTS public.friendships CASCADE;

CREATE TABLE public.friendships (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  friend_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  is_locked boolean DEFAULT false,
  is_favorite boolean DEFAULT false,
  is_archived boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  UNIQUE(user_id, friend_id)
);

ALTER TABLE public.friendships ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can see their friendships" ON friendships;
CREATE POLICY "Users can see their friendships" ON friendships FOR SELECT USING (auth.uid() = user_id OR auth.uid() = friend_id);
DROP POLICY IF EXISTS "Users can insert friendships" ON friendships;
CREATE POLICY "Users can insert friendships" ON friendships FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can update their friendships" ON friendships;
CREATE POLICY "Users can update their friendships" ON friendships FOR UPDATE USING (auth.uid() = user_id OR auth.uid() = friend_id);


-- Fix for status table
DROP TABLE IF EXISTS public.status CASCADE;

CREATE TABLE public.status (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  content text,
  media_url text,
  type text,
  text_style jsonb,
  duration int4,
  expires_at timestamptz,
  created_at timestamptz DEFAULT now(),
  media_type text,
  thumbnail_url text,
  audio_url text,
  storage_paths text[],
  background_color text,
  is_deleted bool DEFAULT false,
  privacy_type text,
  viewer_ids uuid[],
  mentioned_user_ids uuid[],
  encrypted_keys jsonb
);

ALTER TABLE public.status ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all actions for authenticated users" ON public.status FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- Fix for blocked_users table
DROP TABLE IF EXISTS public.blocked_users CASCADE;

CREATE TABLE public.blocked_users (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  blocker_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  blocked_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now(),
  UNIQUE(blocker_id, blocked_id)
);

ALTER TABLE public.blocked_users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all actions for authenticated users" ON public.blocked_users FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- Fix for groups table
DROP TABLE IF EXISTS public.groups CASCADE;

CREATE TABLE public.groups (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name text,
  description text,
  avatar_url text,
  created_by uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.groups ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all actions for authenticated users" ON public.groups FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- Fix for call_logs table
DROP TABLE IF EXISTS public.call_logs CASCADE;

CREATE TABLE public.call_logs (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  caller_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  receiver_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  group_id uuid REFERENCES public.groups(id) ON DELETE CASCADE,
  type text,
  status text,
  duration int4,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.call_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all actions for authenticated users" ON public.call_logs FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- Fix for chat_wallpapers table
DROP TABLE IF EXISTS public.chat_wallpapers CASCADE;

CREATE TABLE public.chat_wallpapers (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  friend_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  wallpaper_url text,
  created_at timestamptz DEFAULT now(),
  UNIQUE(user_id, friend_id)
);

ALTER TABLE public.chat_wallpapers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all actions for authenticated users" ON public.chat_wallpapers FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- Fix for conversations table
DROP TABLE IF EXISTS public.conversations CASCADE;

CREATE TABLE public.conversations (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  type text,
  name text,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all actions for authenticated users" ON public.conversations FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- Fix for conversation_members table
DROP TABLE IF EXISTS public.conversation_members CASCADE;

CREATE TABLE public.conversation_members (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  conversation_id uuid REFERENCES public.conversations(id) ON DELETE CASCADE,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  joined_at timestamptz DEFAULT now(),
  UNIQUE(conversation_id, user_id)
);

ALTER TABLE public.conversation_members ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all actions for authenticated users" ON public.conversation_members FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- Fix for friend_requests table
DROP TABLE IF EXISTS public.friend_requests CASCADE;

CREATE TABLE public.friend_requests (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  sender_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  receiver_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  status text,
  created_at timestamptz DEFAULT now(),
  UNIQUE(sender_id, receiver_id)
);

ALTER TABLE public.friend_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all actions for authenticated users" ON public.friend_requests FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- Fix for group_members table
DROP TABLE IF EXISTS public.group_members CASCADE;

CREATE TABLE public.group_members (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  group_id uuid REFERENCES public.groups(id) ON DELETE CASCADE,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  role text,
  joined_at timestamptz DEFAULT now(),
  UNIQUE(group_id, user_id)
);

ALTER TABLE IF EXISTS public.group_members
DROP CONSTRAINT IF EXISTS group_members_group_id_fkey;

ALTER TABLE public.group_members 
ADD CONSTRAINT group_members_group_id_fkey 
FOREIGN KEY (group_id) 
REFERENCES public.groups (id) 
ON DELETE CASCADE;

ALTER TABLE public.group_members ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all actions for authenticated users" ON public.group_members FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- Fix for ledger table
DROP TABLE IF EXISTS public.ledger CASCADE;

CREATE TABLE public.ledger (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  friend_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  amount numeric,
  description text,
  type text,
  sync_id text,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.ledger ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all actions for authenticated users" ON public.ledger FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- Fix for messages table
DROP TABLE IF EXISTS public.messages CASCADE;

CREATE TABLE public.messages (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  sender_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  receiver_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  message text,
  is_read bool DEFAULT false,
  created_at timestamptz DEFAULT now(),
  file_url text,
  file_name text,
  file_type text,
  file_size int4,
  status text,
  reactions jsonb DEFAULT '{}'::jsonb,
  edited bool DEFAULT false,
  reply_to_id uuid REFERENCES public.messages(id) ON DELETE CASCADE,
  status_id uuid,
  message_type text,
  call_details jsonb,
  group_id uuid REFERENCES public.groups(id) ON DELETE CASCADE,
  conversation_id uuid REFERENCES public.conversations(id) ON DELETE CASCADE,
  reply_to_message_id uuid REFERENCES public.messages(id) ON DELETE CASCADE,
  deleted_at timestamptz
);

ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all actions for authenticated users" ON public.messages FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- Fix for message_reactions table
DROP TABLE IF EXISTS public.message_reactions CASCADE;

CREATE TABLE public.message_reactions (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  message_id uuid REFERENCES public.messages(id) ON DELETE CASCADE,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  emoji text,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.message_reactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all actions for authenticated users" ON public.message_reactions FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- Fix for message_reads table
DROP TABLE IF EXISTS public.message_reads CASCADE;

CREATE TABLE public.message_reads (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  message_id uuid REFERENCES public.messages(id) ON DELETE CASCADE,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  read_at timestamptz DEFAULT now()
);

ALTER TABLE public.message_reads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all actions for authenticated users" ON public.message_reads FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- Fix for notifications table
DROP TABLE IF EXISTS public.notifications CASCADE;

CREATE TABLE public.notifications (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  type text,
  content text,
  related_id uuid,
  is_read bool DEFAULT false,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all actions for authenticated users" ON public.notifications FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- Fix for status_views table
DROP TABLE IF EXISTS public.status_views CASCADE;

CREATE TABLE public.status_views (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  status_id uuid REFERENCES public.status(id) ON DELETE CASCADE,
  viewer_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  viewed_at timestamptz DEFAULT now()
);

ALTER TABLE public.status_views ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all actions for authenticated users" ON public.status_views FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- ==========================================
-- AUTHENTICATION TRIGGER
-- Yeh trigger har naye user ke register hone par
-- automatically profiles table mein ek row insert karta hai
-- ==========================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, phone)
  VALUES (
    NEW.id,
    NEW.email,
    NEW.raw_user_meta_data->>'phone'
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Reload schema cache
NOTIFY pgrst, 'reload schema';

-- Update statuses table with new Hybrid E2EE keys and media fields
ALTER TABLE public.statuses
ADD COLUMN IF NOT EXISTS encrypted_keys JSONB,
ADD COLUMN IF NOT EXISTS mentioned_user_ids UUID[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS audio_url TEXT,
ADD COLUMN IF NOT EXISTS thumbnail_url TEXT;

-- Reload schema cache again
NOTIFY pgrst, 'reload schema';
-- Add new privacy columns without dropping tables
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS dp_privacy text DEFAULT 'everyone';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS dp_selected_friends uuid[] DEFAULT '{}';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS hide_dp_in_search boolean DEFAULT false;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS about_privacy text DEFAULT 'everyone';

-- Disappearing Messages Support
ALTER TABLE public.friendships ADD COLUMN IF NOT EXISTS disappearing_duration integer DEFAULT 0;
ALTER TABLE public.messages ADD COLUMN IF NOT EXISTS expires_at timestamptz;

-- ==========================================
-- SCHEDULED MESSAGES & CRON JOB
-- ==========================================
CREATE EXTENSION IF NOT EXISTS pg_cron;

DROP TABLE IF EXISTS public.scheduled_messages CASCADE;

CREATE TABLE public.scheduled_messages (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  sender_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  receiver_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  group_id uuid REFERENCES public.groups(id) ON DELETE CASCADE,
  message text,
  file_url text,
  file_type text,
  file_name text,
  file_size numeric,
  message_type text DEFAULT 'text',
  scheduled_at timestamptz NOT NULL,
  status text DEFAULT 'pending',
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.scheduled_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can insert scheduled messages" ON public.scheduled_messages FOR INSERT WITH CHECK (auth.uid() = sender_id);
CREATE POLICY "Users can view their scheduled messages" ON public.scheduled_messages FOR SELECT USING (auth.uid() = sender_id);
CREATE POLICY "Users can update their scheduled messages" ON public.scheduled_messages FOR UPDATE USING (auth.uid() = sender_id);
CREATE POLICY "Users can delete their scheduled messages" ON public.scheduled_messages FOR DELETE USING (auth.uid() = sender_id);

-- Function to process scheduled messages
CREATE OR REPLACE FUNCTION public.process_scheduled_messages()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- Insert pending messages whose time has come into the main messages table
  INSERT INTO public.messages (sender_id, receiver_id, group_id, message, file_url, file_type, file_name, file_size, message_type, status, is_read, created_at)
  SELECT sender_id, receiver_id, group_id, message, file_url, file_type, file_name, file_size, message_type, 'sent', false, now()
  FROM public.scheduled_messages
  WHERE status = 'pending' AND scheduled_at <= now();

  -- Mark them as sent
  UPDATE public.scheduled_messages
  SET status = 'sent'
  WHERE status = 'pending' AND scheduled_at <= now();
END;
$$;

-- Schedule the cron job to run every minute
-- Note: 'process_scheduled_msgs_job' is the job name
SELECT cron.unschedule('process_scheduled_msgs_job');
SELECT cron.schedule('process_scheduled_msgs_job', '* * * * *', 'SELECT public.process_scheduled_messages()');

-- ==========================================
-- NINJA VAULT (GHOST CHATS) SUPPORT
-- ==========================================
ALTER TABLE public.friendships ADD COLUMN IF NOT EXISTS is_hidden BOOLEAN DEFAULT FALSE;
ALTER TABLE public.group_members ADD COLUMN IF NOT EXISTS is_hidden BOOLEAN DEFAULT FALSE;



-- Add expires_at to messages for disappearing messages
ALTER TABLE messages ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP WITH TIME ZONE NULL;

-- Add is_hidden for ghost chats (Ninja Vault)
ALTER TABLE friendships ADD COLUMN IF NOT EXISTS is_hidden BOOLEAN DEFAULT FALSE;
ALTER TABLE group_members ADD COLUMN IF NOT EXISTS is_hidden BOOLEAN DEFAULT FALSE;

-- Reload schema cache
NOTIFY pgrst, 'reload schema';
