-- Add missing columns to profiles table

ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS phone TEXT,
ADD COLUMN IF NOT EXISTS bio TEXT,
ADD COLUMN IF NOT EXISTS gender TEXT,
ADD COLUMN IF NOT EXISTS show_email BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS show_phone BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS show_bio BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS allow_status_download BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS last_lat NUMERIC,
ADD COLUMN IF NOT EXISTS last_long NUMERIC,
ADD COLUMN IF NOT EXISTS about TEXT;
